version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm run build
  build:
    commands:
      - npm run build
  artifacts:
    files:
      - dist/*
