# Simple workflow for deploying static content to GitHub Pages
name: create preview environment and run e2e

on: 
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - main

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write
  issues: write

# Allow one concurrent deployment
concurrency: preview-${{ github.ref }}

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build -- --base "/actions-example/pr-preview/pr-${{github.event.number}}/"
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/
      - name: wait for preview to become available
        run: sleep 120
      - name: run e2e
        run: CYPRESS_BASE_URL=https://cfry2.github.io/actions-example/pr-preview/pr-${{github.event.number}} npm run e2e
