name: 
on: 
    pull_request:
        branches:
            - main
permissions:
  pull-requests: write
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: 'npm'
            - name: Install dependencies
              run: npm install
            - name: Run unit tests
              run: npm test
            - name: output dir
              run: ls -al
            - name: list path
              run: pwd
            - name: 'Report Coverage'
              # Set if: always() to also generate the report if tests are failing
              # Only works if you set `reportOnFailure: true` in your vite config as specified above
              if: always() 
              uses:  davelosert/vitest-coverage-report-action@v2
    vulnerabilities:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Snyk
        uses: snyk/actions@0.4.0
  
          