name: 
on: 
    pull_request:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: 'npm'
            - name: Install dependencies
              run: npm install
            - name: Run unit tests
              run: npm test
          